package com.example.spring.demo.svg;

public class Schermate {

    public String Carico = "\n" +
            "\n" +
            "NODE:RAMPA1,ENDOF:A1UL3\n" +
            "\n" +
            "NODE:FERRICOSTART\n" +
            "\n" +
            "NODE:RAMPA2,ENDOF:A1UL12\n" +
            "\n" +
            "NODE:FI904B,MEASUREOF:P904B,TYPE:M3/H\n" +
            "\n" +
            "NODE:FI954,MEASUREOF:a1UL3,TYPE:M3/H\n" +
            "\n" +
            "NODE:A1UL14,ENDOF:A1UL12\n" +
            "\n" +
            "NODE:a1UL1,ENDOF:a1UL3\n" +
            "\n" +
            "NODE:FERROSOSTART\n" +
            "\n" +
            "NODE:S-904D,ENDOF:FERRICOSTART+a1UL14\n" +
            "\n" +
            "NODE:a1UL2,ENDOF:a1UL3\n" +
            "\n" +
            "NODE:A1UL13,ENDOF:A1UL12\n" +
            "\n" +
            "NODE:a1UL3,ENDOF:P954\n" +
            "\n" +
            "NODE:A1UL12,ENDOF:P904B\n" +
            "\n" +
            "NODE:S-904E,ENDOF:FERRICOSTART+a1UL13\n" +
            "\n" +
            "NODE:S-954A,ENDOF:FERROSOSTART+a1UL1\n" +
            "\n" +
            "NODE:LI904D,MEASUREOF:S-904D,TYPE:%\n" +
            "\n" +
            "NODE:S-954B,ENDOF:a1UL2+FERROSOSTART\n" +
            "\n" +
            "NODE:LI904E,MEASUREOF:S-904E,TYPE:%\n" +
            "\n" +
            "NODE:LI954B,MEASUREOF:S-954B,TYPE:%\n" +
            "\n" +
            "NODE:a1UL5,ENDOF:S-954B\n" +
            "\n" +
            "NODE:P904B,ENDOF:A1UL11\n" +
            "\n" +
            "NODE:LI954A,MEASUREOF:S-954A,TYPE:%\n" +
            "\n" +
            "NODE:LI954B,MEASUREOF:S-954B,TYPE:%\n" +
            "\n" +
            "NODE:a1UL8,ENDOF:S-904D\n" +
            "\n" +
            "NODE:P954,ENDOF:a1UL4\n" +
            "\n" +
            "NODE:a1UL10,ENDOF:S-904E\n" +
            "\n" +
            "NODE:a1UL9,ENDOF:S-904E+a1UL8\n" +
            "\n" +
            "NODE:a1UL6,ENDOF:S-954B\n" +
            "\n" +
            "NODE:A1UL11,ENDOF:A1UL10\n" +
            "\n" +
            "NODE:a1UL7,ENDOF:S-954A\n" +
            "\n" +
            "NODE:a1UL4,ENDOF:a1UL6+a1UL7\n";


    public String Carico2 = "\n" +
            "\n" +
            "NODE:P904B\n" +
            "\n" +
            "NODE:P954\n" +
            "\n" +
            "NODE:XV904DE_2,ENDOF:P904B\n" +
            "\n" +
            "NODE:XV904DE_1,ENDOF:P904B\n" +
            "\n" +
            "NODE:XV954AB,ENDOF:P954\n" +
            "\n" +
            "NODE:FERRICOPOTABILESTART\n" +
            "\n" +
            "NODE:A2UL14,ENDOF:FERRICOPOTABILESTART\n" +
            "\n" +
            "NODE:A2UL13,ENDOF:S-904A\n" +
            "\n" +
            "NODE:FERRICONONPOTABILESTART\n" +
            "\n" +
            "NODE:XV904ABC_1,ENDOF:A2UL13+A2UL12+A2UL11+A2UL10\n" +
            "\n" +
            "NODE:A2UL12,ENDOF:S-904B\n" +
            "\n" +
            "NODE:XV904ABC_2,ENDOF:A2UL10+A2UL11+A2UL12+A2UL13\n" +
            "\n" +
            "NODE:A2UL11,ENDOF:S-904C\n" +
            "\n" +
            "NODE:A2UL10,ENDOF:P904A\n" +
            "\n" +
            "NODE:FI900,MEASUREOF:P904A\n" +
            "\n" +
            "NODE:S-904A,ENDOF:FERRICONONPOTABILESTART\n" +
            "\n" +
            "NODE:LI904C,MEASUREOF:S-904C,TYPE:%\n" +
            "\n" +
            "NODE:S-904B,ENDOF:A2UL14+FERRICONONPOTABILESTART\n" +
            "\n" +
            "NODE:S-904C,endof:FERRICONONPOTABILESTART+A2UL14\n" +
            "\n" +
            "NODE:LI904B,MEASUREOF:S-904B,TYPE:%\n" +
            "\n" +
            "NODE:A2TRUCK2EXIT,ENDOF:XV904DE_2\n" +
            "\n" +
            "NODE:A2TRUCK1EXIT,ENDOF:XV904ABC_1\n" +
            "\n" +
            "NODE:A2UL19,ENDOF:S-904C\n" +
            "\n" +
            "NODE:UL17,ENDOF:S-904B\n" +
            "\n" +
            "NODE:A2UL16,ENDOF:S-904B\n" +
            "\n" +
            "NODE:UL18,ENDOF:S-904C\n" +
            "\n" +
            "NODE:P904A,ENDOF:A2UL20\n" +
            "\n" +
            "NODE:A2UL20,ENDOF:A2UL19\n" +
            "\n" +
            "NODE:A2UL15,ENDOF:S-904A\n" +
            "\n" +
            "NODE:IBCEXIT,ENDOF:A2UL13+A2UL12+A2UL11+A2UL10\n";

    public String Ferroso = "\n" +
            "\n" +
            "\n" +
            "NODE:FERROSORISODOTTOATOSCAGGIOEXIT,ENDOF:UL18\n" +
            "\n" +
            "NODE:P955START\n" +
            "\n" +
            "NODE:K981A,ENDOF:UL12+C981\n" +
            "\n" +
            "NODE:P52B,ENDOF:S52START\n" +
            "\n" +
            "NODE:FI980-2,MEASUREOF:UL19,TYPE:M3/H\n" +
            "\n" +
            "NODE:ATMOSFERASTART\n" +
            "\n" +
            "NODE:TI981,MEASUREOF:UL11,TYPE:C\n" +
            "\n" +
            "NODE:S52START\n" +
            "\n" +
            "NODE:K981B,ENDOF:UL12+C981\n" +
            "\n" +
            "NODE:UL18,ENDOF:P980A\n" +
            "\n" +
            "NODE:FIC980,MEASUREOF:UL19,TYPE:M3/H\n" +
            "\n" +
            "NODE:FI981,MEASUREOF:UL11,TYPE:M3/H\n" +
            "\n" +
            "NODE:UL12,ENDOF:ATMOSFERASTART\n" +
            "\n" +
            "NODE:C905EXIT,ENDOF:C980+XV986_2\n" +
            "\n" +
            "NODE:LIC981,MEASUREOF:UL11+C981,TYPE:%\n" +
            "\n" +
            "NODE:PI981-1,MEASUREOF:C981,TYPE:MMH20\n" +
            "\n" +
            "NODE:ACQUADEMISTART\n" +
            "\n" +
            "NODE:MS980START\n" +
            "\n" +
            "NODE:C980,ENDOF:UL19+UL17+UL16\n" +
            "\n" +
            "NODE:UL11,ENDOF:ACQUADEMISTART\n" +
            "\n" +
            "NODE:UL19,ENDOF:P980A\n" +
            "\n" +
            "NODE:C981,ENDOF:START1+UL12+UL11\n" +
            "\n" +
            "NODE:TI980,MEASUREOF:E980\n" +
            "\n" +
            "NODE:P981A,ENDOF:P981B\n" +
            "\n" +
            "NODE:PI981_2,MEASUREOF:C981,TYPE:MMH2O\n" +
            "\n" +
            "NODE:FIC982_2,MEASUREOF:S982,TYPE:M3/H\n" +
            "\n" +
            "\n" +
            "NODE:P981B,ENDOF:C981+P984+P981A+P984\n" +
            "\n" +
            "NODE:PI980_1,MEASUREOF:C980,TYPE:MMH2O\n" +
            "\n" +
            "NODE:E980,ENDOF:UL13\n" +
            "\n" +
            "NODE:UL17,ENDOF:UL14+P982A+P982B+S982\n" +
            "\n" +
            "NODE:PIC980,MEASUREOF:R980+UL12,TYPE:MMH20\n" +
            "\n" +
            "NODE:TI987,MEASUREOF:R986,TYPE:C\n" +
            "\n" +
            "NODE:AI981,MEASUREOF:C981,TYPE:PH\n" +
            "\n" +
            "NODE:PI980_2,MEASUREOF:C980,TYPE:MMH20\n" +
            "\n" +
            "NODE:XV986_2,ENDOF:XV986_1\n" +
            "\n" +
            "NODE:KOHSTART\n" +
            "\n" +
            "NODE:TI980_1,MEASUREOF:R980,TYPE:C\n" +
            "\n" +
            "NODE:UL13,ENDOF:P985\n" +
            "\n" +
            "NODE:P984,ENDOF:KOHSTART\n" +
            "\n" +
            "NODE:UL16,ENDOF:XV986_1\n" +
            "\n" +
            "NODE:START1\n" +
            "\n" +
            "NODE:LIC985,MEASUREOF:UL13+S985,TYPE:%\n" +
            "\n" +
            "NODE:XV986_1,ENDOF:START\n" +
            "\n" +
            "NODE:START\n" +
            "\n" +
            "NODE:N2START1\n" +
            "\n" +
            "NODE:R986,ENDOF:MS980START+P955START+P52B\n" +
            "\n" +
            "NODE:TI980_2,MEASUREOF:C980,TYPE:C\n" +
            "\n" +
            "NODE:FIC986,MEASUREOF:UL16,TYPE:NM3/H\n" +
            "\n" +
            "NODE:S920EXIT,ENDOF:P986\n" +
            "\n" +
            "NODE:WI986,MEASUREOF:R986,TYPE:KG\n" +
            "\n" +
            "NODE:R980,ENDOF:XV983+UL10+HCLSTART+START1+N2START1\n" +
            "\n" +
            "NODE:PI986,MEASUREOF:XV986_1,TYPE:MMH2O\n" +
            "\n" +
            "NODE:WI980,MEASUREOF:R980,TYPE:KG\n" +
            "\n" +
            "NODE:XV986,ENDOF:R986\n" +
            "\n" +
            "NODE:S-904E,ENDOF:UL15\n" +
            "\n" +
            "NODE:S985,ENDOF:START1+MS980START+R980+E980\n" +
            "\n" +
            "NODE:TI986,MEASUREOF:XV986_1,TYPE:C\n" +
            "\n" +
            "NODE:P985,ENDOF:S985\n" +
            "\n" +
            "NODE:S-904D,ENDOF:UL15\n" +
            "\n" +
            "NODE:P986,ENDOF:XV986\n" +
            "\n" +
            "NODE:TI982,MEASUREOF:E981,TYPE:C\n" +
            "\n" +
            "NODE:FIC982_1,MEASUREOF:UL14,TYPE:M3/H,\n" +
            "\n" +
            "NODE:UL15,ENDOF:E981\n" +
            "\n" +
            "NODE:UL14,ENDOF:HCLSTART+UL10\n" +
            "\n" +
            "NODE:N2START2\n" +
            "\n" +
            "NODE:FIC981_2,MEASUREOF:UL10,TYPE:M3/H\n" +
            "\n" +
            "NODE:S980,ENDOF:MS980START\n" +
            "\n" +
            "NODE:E981,ENDOF:S982+P982A+P982B\n" +
            "\n" +
            "NODE:LIC982,MEASUREOF:S982+UL15,TYPE:%\n" +
            "\n" +
            "NODE:XV983,ENDOF:N2START2\n" +
            "\n" +
            "NODE:S982,ENDOF:C980\n" +
            "\n" +
            "NODE:P981ABSTART\n" +
            "\n" +
            "NODE:UL10,ENDOF:P981ABSTART\n" +
            "\n" +
            "NODE:LIC980,MEASUREOF:S980,TYPE:%\n" +
            "\n" +
            "NODE:P980A,ENDOF:S980\n" +
            "\n" +
            "NODE:AI982,MEASUREOF:S982\n" +
            "\n" +
            "NODE:P982B,ENDOF:P982A\n" +
            "\n" +
            "NODE:HCLSTART\n" +
            "\n" +
            "NODE:P982A,ENDOF:S982\n";

    public String FeCl3 = "\n" +
            "\n" +
            "\n" +
            "NODE:FIC901,MEASUREOF:UL40,TYPE:L/HR\n" +
            "\n" +
            "NODE:P-901START\n" +
            "\n" +
            "NODE:FIC909-2,MEASUREOF:UL45,TYPE:M3/H\n" +
            "\n" +
            "NODE:C905EXIT,ENDOF:C-910\n" +
            "\n" +
            "NODE:P-900START\n" +
            "\n" +
            "NODE:PI909-2,MEASUREOF:C-909,TYPE:MMH20\n" +
            "\n" +
            "NODE:UL40,ENDOF:S-901+900-P910C+900-P910A+900-P910B\n" +
            "\n" +
            "UL45,ENDOF:P-901START,P-900START\n" +
            "\n" +
            "NODE:C-910,ENDOF:UL40+UL41+UL42\n" +
            "\n" +
            "NODE:FIC902,MEASUREOF:UL41,TYPE:L/HR\n" +
            "\n" +
            "NODE:CV-905-1,ENDOF:GASDAGPSSTART\n" +
            "\n" +
            "NODE:FIC253_4,MEASUREOF:UL44,TYPE:NM3/H\n" +
            "\n" +
            "NODE:GASDAGPSSTART\n" +
            "\n" +
            "NODE:FIC912,MEASUREOF:UL42,TYPE:NM3/H\n" +
            "\n" +
            "NODE:UL41,ENDOF:P902A+P902B+P909\n" +
            "\n" +
            "NODE:CL2-DA-K2204START\n" +
            "\n" +
            "NODE-RH910,MEASUREOF:P902A\n" +
            "\n" +
            "NODE:UL44,ENDOF:XV901A+XV901B\n" +
            "\n" +
            "NODE:PI909-1,MEASUREOF:C-909,TYPE:MMH20\n" +
            "\n" +
            "NODE:XV901A,ENDOF:CL2-DA-K2204START\n" +
            "\n" +
            "NODE:S-954A,ENDOF:900-P910C+S-901+900-P910A+900-P910B\n" +
            "\n" +
            "NODE:UL42,ENDOF:XV912_1+XV912_2\n" +
            "\n" +
            "NODE:XV912_1,ENDOF:CL2-DA-K2204START\n" +
            "\n" +
            "NODE:S-954B,ENDOF:900-P910C+S-901+900-P910A+900-P910B\n" +
            "\n" +
            "NODE:C-909,ENDOF:UL44+UL45+CV-905-1\n" +
            "\n" +
            "NODE:DEGASAMENTOEXIT,ENDOF:XV912_2+XV901B\n" +
            "\n" +
            "NODE:PI901,MEASUREOF:XV901A,TYPE:MMH2O\n" +
            "\n" +
            "NODE:XV912_2,ENDOF:XV912_1\n" +
            "\n" +
            "NODE:TI900,MEASUREOF:C-910,TYPE:C\n" +
            "\n" +
            "NODE:LIC910,MEASUREOF:S-910,TYPE-%\n" +
            "\n" +
            "NODE:XV901B,ENDOF:XV901A\n" +
            "\n" +
            "NODE:LIC909,MEASUREOF:S-909,TYPE-%\n" +
            "\n" +
            "NODE:UL43,ENDOF:P902A+P902B+P909\n" +
            "\n" +
            "NODE:UL46,ENDOF:P909\n" +
            "\n" +
            "NODE:R980,ENDOF:UL43\n" +
            "\n" +
            "NODE:MS-922,ENDOF:UL46\n" +
            "\n" +
            "NODE:RH900,MEASUREOF:S-909,TYPE:MV\n" +
            "\n" +
            "???\n" +
            "\n" +
            "NODE:S-909,ENDOF:C-909\n" +
            "\n" +
            "NODE:S-901,ENDOF:900-P910A+900-P910B\n" +
            "\n" +
            "NODE:HC900,MEASUREOF:UL46,TYPE:%\n" +
            "\n" +
            "NODE:S-900,ENDOF:UL47\n" +
            "\n" +
            "NODE:S-910,ENDOF:C-910\n" +
            "\n" +
            "NODE:S-910ASTART\n" +
            "\n" +
            "NODE:UL47,ENDOF:P909\n" +
            "\n" +
            "NODE:P902B,ENDOF:S-910+P902A\n" +
            "\n" +
            "NODE:900-P910B,ENDOF:ATBSTART2+900-P910A\n" +
            "\n" +
            "NODE:900-P910C,ENDOF:S-910ASTART+ATBSTART1\n" +
            "\n" +
            "NODE:ATBSTART2\n" +
            "\n" +
            "NODE:P902A,ENDOF:S-910\n" +
            "\n" +
            "NODE:P909,ENDOF:S-909\n" +
            "\n" +
            "NODE:900-P910A,ENDOF:S-901+ATBSTART2\n" +
            "\n" +
            "NODE:ATBSTART1\n";
}
