name: Build and push Docker image to GCR only with a dockerfile

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: explainable
  IMAGE_VERSION: v1.0.1
  GCR_PROJECT_ID: virtual-plexus-379510 # questo valore si trova sotto il nome del progetto al link: https://console.cloud.google.com/
  GCR_REPOSITORY_NAME: explainable
  CLOUD_RUN_SERVICE_NAME: explainable-service


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} .
      - name: Tag Docker image
        run: docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} eu.gcr.io/${{ env.GCR_PROJECT_ID }}/${{ env.GCR_REPOSITORY_NAME }}:${{ env.IMAGE_VERSION }}
      - name: Push Docker image
        run: docker push  eu.gcr.io/${{ env.GCR_PROJECT_ID }}/${{ env.GCR_REPOSITORY_NAME }}:${{ env.IMAGE_VERSION }}



      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ env.GCR_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Deploy Docker image to Cloud Run
        run: gcloud run deploy ${{ env.CLOUD_RUN_SERVICE_NAME }} \
          --image=eu.gcr.io/${{ env.GCR_PROJECT_ID }}/${{ env.GCR_REPOSITORY_NAME }}:${{ env.IMAGE_VERSION }} \
          --platform=managed \
          --region=europe-west8 \
          --allow-unauthenticated

