#name: Build and push Docker images to GCR with dockercompose
#
#on:
#  push:
#    branches:
#      - master
#
#env:
#  IMAGE_VERSION: v1.0.1
#  GCR_PROJECT_ID: virtual-plexus-379510
#  GCR_REPOSITORY_NAME: explainable
#
#jobs:
#  build-and-push:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Login to GCR
#        uses: docker/login-action@v1
#        with:
#          registry: eu.gcr.io
#          username: _json_key
#          password: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}
#
#      - name: Build and push Docker images
#        run: |
#          docker-compose build
#          docker-compose push
