name: Build and push Docker image to GCR

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: explainable
  IMAGE_VERSION: 1.0.1
  GCR_PROJECT_ID: whoteach-dev
  GCR_REPOSITORY_NAME: explainable
  GCR_REPOSITORY_URL: eu.gcr.io/${{ env.GCR_PROJECT_ID }}/${{ env.GCR_REPOSITORY_NAME }}



jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} .
      - name: Tag Docker image
        run: docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} ${{ env.GCR_REPOSITORY_URL }}:${{ env.IMAGE_VERSION }}
      - name: Push Docker image
        run: docker push ${{ env.GCR_REPOSITORY_URL }}:${{ env.IMAGE_VERSION }}
